apiVersion: apps/v1
kind: Deployment
metadata:
  name: insuretech-app
spec:
  selector:
    matchLabels:
      app: insuretech-app
  replicas: 1
  template:
    metadata:
      labels:
        app: insuretech-app
    spec:
      containers:
      - name: scaletestapp
        image: shestera/scaletestapp:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "30Mi"
          limits:
            memory: "30Mi"
