apiVersion: v1
kind: Service
metadata:
  name: insuretech-app-service
  labels:
    app: insuretech-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: insuretech-app
  type: NodePort
